version: '3.8'

services:
  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - redis-py
    ports:
      - 8000:8000

  redis-py:
    image: redis:7.2-rc3-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
