version: '3.8'

services:
  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    ports:
      - 8000:8000

  mongo:
    image: iondv/arm32-mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
