# Usa una imagen oficial de Python como base
FROM python:3.11

# Establece un directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos al contenedor
COPY ./requirements.txt /app/

# Instala las dependencias de Python
RUN pip install -r requirements.txt

# Copia el resto del código de tu aplicación al contenedor
COPY . /app

# Ejecuta la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
